[[session]]
name = "Downloads ðŸ“¥"
path = "~/Downloads"
startup_command = "ls -al"

[[session]]
name = "Repos ðŸ“¥"
path = "~/workspace/repos/"
startup_command = "ls -al"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "nvim config"
path = "~/.config/nvim"
startup_command = "nvim ."

[[session]]
name = "alacritty config"
path = "~/.config/alacritty"
startup_command = "nvim alacritty.toml"

name = "ghostty config"
path = "~/.config/ghostty"
startup_command = "nvim config"

